services:
  backend:
    ports:
      - "4000:4000"
    container_name: backend_mern
    build: ./backend
    env_file:
      - ./.env.example

  frontend:
    ports:
      - "5173:5173"
    build: ./frontend
    container_name: frontend_mern
  mongo:
    image: mongo:7
    container_name: mongo_local
    ports:
      - "27017:27017"